# Generated by Django 4.0.3 on 2022-03-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productitem_size_productitemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productitem',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=20),
            preserve_default=False,
        ),
    ]
