# Generated by Django 4.0.3 on 2022-03-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productitem_bestseller_productitem_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitemimage',
            name='image',
            field=models.ImageField(upload_to='productItemImage'),
        ),
    ]
