# Generated by Django 4.0.3 on 2022-03-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productitem_compound_productitem_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='bestseller',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='new',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='vendor_code',
        ),
        migrations.AddField(
            model_name='product',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='compound',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default=10000, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='products.product'),
        ),
    ]
