# Generated by Django 4.0.3 on 2022-03-29 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_color_alter_productitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='color',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
    ]
