# Generated by Django 4.0.3 on 2022-03-29 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='products.color'),
        ),
        migrations.AlterField(
            model_name='productitemimage',
            name='productItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item_images', to='products.productitem'),
        ),
    ]
