# Generated by Django 4.0.3 on 2022-03-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productitem_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
    ]
