# Generated by Django 4.0.3 on 2022-03-31 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='color',
        ),
        migrations.AddField(
            model_name='productitem',
            name='color',
            field=models.ManyToManyField(to='products.color'),
        ),
        migrations.AlterField(
            model_name='size',
            name='productItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.productitem'),
        ),
    ]
