# Generated by Django 4.0.3 on 2022-04-11 04:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='aboutImage')),
                ('image2', models.ImageField(upload_to='aboutImage')),
                ('image3', models.ImageField(upload_to='aboutImage')),
                ('header', models.CharField(max_length=55)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
