# Generated by Django 4.0.3 on 2022-04-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_alter_favorite_products_alter_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='page', max_length=255),
            preserve_default=False,
        ),
    ]
