# Generated by Django 4.0.3 on 2022-04-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_advantage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='main.slider'),
        ),
    ]
