# Generated by Django 4.0.3 on 2022-04-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_faqimage_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='headerImage')),
                ('text', models.CharField(max_length=255)),
                ('phone_num', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Number', 'Number'), ('Mail', 'Mail'), ('Telegram', 'Telegram'), ('Instagram', 'Instagram'), ('Whatsapp', 'Whatsapp')], max_length=255)),
                ('link', models.URLField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='faqimage',
            name='image',
            field=models.ImageField(upload_to='faqImage'),
        ),
    ]
