# Generated by Django 4.0.3 on 2022-04-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_header_alter_faqimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
