# Generated by Django 4.0.3 on 2022-04-11 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_header_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='link',
        ),
        migrations.RemoveField(
            model_name='header',
            name='type',
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Number', 'Number'), ('Mail', 'Mail'), ('Telegram', 'Telegram'), ('Instagram', 'Instagram'), ('Whatsapp', 'Whatsapp')], max_length=255)),
                ('link', models.URLField(blank=True, max_length=255)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.header')),
            ],
        ),
    ]
