# Generated by Django 4.0.3 on 2022-04-12 04:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_header_link_remove_header_type_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=55)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Header', 'verbose_name_plural': 'Header'},
        ),
        migrations.AlterField(
            model_name='footer',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='main.header'),
        ),
    ]
