# Generated by Django 4.0.3 on 2022-04-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_public_alter_header_options_alter_footer_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('back_call', models.BooleanField()),
                ('called', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.URLField(max_length=255)),
                ('telegram', models.URLField(max_length=255)),
            ],
        ),
    ]
